FROM redis:latest as starter-gin-redis
FROM mysql:latest as starter-mysql
# 初始化启动时要创建的数据库的名称
ENV MYSQL_DATABASE: 'starter'
ENV MYSQL_USER: 'root'
ENV MYSQL_ROOT_PASSWORD: 'abczzhstarter'

FROM golang:alpine as starter-server
LABEL MAINTAINER="zzg<zzh1586169624@163.com>"
WORKDIR /usr/src/app
COPY .. .

RUN go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go env -w CGO_ENABLED=0 \
    && go env \
    && go mod tidy \
    && go build -o server . \
    && mkdir "upload" \
    && mkdir "static" \
ENTRYPOINT ./server -c ./deploy -t yaml -n config-dev
EXPOSE 80



